- name: Deploy an EC2 instance in AWS
  hosts: localhost
  gather_facts: no
  collections:
    - amazon.aws
  vars:
    # Default instance type can be overridden via --extra-vars or environment
    instance_type: t2.micro
    image_id: ami-0900fe555666598a2
  environment:
    AWS_REGION: us-east-2
  tasks:
    - name: Create security group
      amazon.aws.ec2_security_group:
        name: sample-app-ansible
        description: Allow HTTP and SSH traffic
        rules:
          - proto: tcp
            ports: [8080]
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
      register: aws_security_group

    - name: Create a new EC2 key pair
      amazon.aws.ec2_key:
        name: ansible-ch2
        file_name: ansible-ch2.key
      no_log: true
      register: aws_ec2_key_pair

    - name: Create EC2 instance with Amazon Linux 2
      amazon.aws.ec2_instance:
        name: sample-app-ansible
        key_name: "{{ aws_ec2_key_pair.key.name }}"
        instance_type: "{{ instance_type }}"
        security_group: "{{ aws_security_group.group_id }}"
        image_id: "{{ image_id }}"
        wait: yes
        wait_timeout: 500
        tags:
          Ansible: ch2_instances
      register: ec2_instance

    - name: Display instance information
      debug:
        msg: "Instance {{ ec2_instance.instances[0].instance_id }} created with IP {{ ec2_instance.instances[0].public_ip_address }}"
