plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  instance-state-name: running
  tag:Ansible: ch2_instances
keyed_groups:
  - key: tags.Ansible
    leading_separator: ''
compose:
  ansible_host: public_ip_address
